---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Start VMs (background)
      shell: |
        {{ vm_launch_command }}
      vars:
        vm_name: "{{ item }}"
      loop: "{{ nodes | dict2items | map(attribute='key') | list }}"
      loop_control:
        label: "{{ item }}"
      async: 3600
      poll: 0
      delegate_to: localhost

    - name: Report started VMs
      debug:
        msg: "Started VM(s): {{ nodes | dict2items | map(attribute='key') | join(', ') }}"
