---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    repo_root: "{{ playbook_dir | dirname }}"
    disk_dir: "{{ repo_root }}/build/disks"
    base_image: "{{ repo_root }}/qemu/images/debian-12-genericcloud-amd64.qcow2"
    disk_format: "qcow2"

  vars_files:
    - "{{ repo_root }}/cloud-init/vars.yml"

  tasks:
    - name: Ensure disk directory exists
      file:
        path: "{{ disk_dir }}"
        state: directory
        mode: "0777"

    - name: Create disks for all VMs
      command:
        cmd: "cp {{ base_image }} {{ disk_dir }}/{{ item.key }}.{{ disk_format }}"
      loop: "{{ nodes | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      register: disk_creation
      changed_when: disk_creation.rc == 0
