---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    repo_root: "{{ playbook_dir | dirname }}"
    run_script: "{{ repo_root }}/qemu/run.sh"
    disk_dir: "{{ repo_root }}/build/disks"
    cloud_init_dir: "{{ repo_root }}/build/cloud-init"
    net_mode: "bridged"

  vars_files:
    - "{{ repo_root }}/cloud-init/vars.yml"

  tasks:
    - name: Start VMs (background)
      shell: >-
        sudo -n {{ run_script }} {{ item }} {{ disk_dir }}/{{ item }}.qcow2 {{ cloud_init_dir }}/{{ item }}/{{ item }}.iso
        > /tmp/qemu-{{ item }}.log 2>&1
      environment:
        NET_MODE: "{{ net_mode }}"
        NET_IF: "{{ bridge_interface }}"
      async: 3600
      poll: 0
      loop: "{{ nodes | dict2items | map(attribute='key') | list }}"
      loop_control:
        label: "{{ item }}"

    - name: Report started VMs
      debug:
        msg: "Started VM(s): {{ nodes | dict2items | map(attribute='key') | join(', ') }}"
